crud/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$',views.list,name='index'),

    url(r'^create/$',views.create,name='create'),
    url(r'^update/(?P<id>\d+)/$',views.update,name='update'),
    url(r'^delete/(?P<id>\d+)/$',views.delete,name='delete'),
    url(r'^reporte/$',views.ReportePersonalizadoExcel.as_view(),name='reporte'),
]

queryset/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'queryset.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^',include('crud.urls',namespace='crud',app_name='crud')),
]

templates/productos/create.html
{% extends 'base.html' %}
{% block content %}
    <h2>Registro</h2>
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Guardad</button>
        <a href="{% url 'crud:index' %}" class="btn btn-danger">Cancelar</a>
    </form>
{% endblock %}

templates/productos/delete.html
{% extends 'base.html' %}
{% block content %}
    <h2>Registro</h2>
    <form action="" method="POST">
        {% csrf_token %}
        <h2>Esta seguro de eliminar el registro {{descripcion}}</h2>
        <button type="submit" class="btn btn-danger">Eliminar</button>
        <a href="{% url 'crud:index' %}" class="btn btn-danger">Cancelar</a>
    </form>
{% endblock %}

templates/productos/index.html
{% extends 'base.html' %}
{% block content %}
    <a href="{% url 'crud:create' %}" class="btn btn-primary">Crear</a>
    <a href="{% url 'crud:reporte'%}" class="btn btn-primary">Reporte en excel</a>
    <table class="table table-dark striped mt-3">
        <thead>
            <tr>
                <th scope="col">ID</th>
                <th scope="col">MARCA</th>
                <th scope="col">MODELO</th>
                <th scope="col">DESCRIPCION</th>
                <th scope="col">FECHA</th>
                <th scope="col">CANTIDAD</th>
                <th scope="col">PRECIO</th>
                <th scope="col">TOTAL</th>
                <th scope="col">ACCION</th>
            </tr>
        </thead>
        <tbody>
            {% for producto in productos%}
            <tr>
                <td>{{producto.id}}</td>
                <td>{{producto.marca}}</td>
                <td>{{producto.modelo}}</td>
                <td>{{producto.descripcion}}</td>
                <td>{{producto.fecha}}</td>
                <td>{{producto.cantidad}}</td>
                <td>{{producto.precio}}</td>
                <td>{{producto.total}}</td>
                <td>
                    <a href="{% url 'crud:update' producto.id %}" class="btn btn-primary">Editar</a>
                    <a href="{% url 'crud:delete' producto.id %}" class="btn btn-danger">Eliminar</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}